---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-project
  region: us-east-1
  
vpc:
  id: vpc-0301c778593ec7860                 #replace with VPC id
  cidr: 10.0.0.0/16
  subnets:
    public:
      frontend-subnet-1a:
        id: subnet-094cd496d1c42e6fb      #replace with subnet ID
        cidr: 10.0.0.0/18
      frontend-subnet-1b:
        id: subnet-07c90f7a883f55d74           #replace with subnet ID
        cidr: 10.0.64.0/18
  
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  publicAccessCIDRs: ["0.0.0.0/0"] #piblic access to the cluster. not safe

managedNodeGroups:
  - name: ng-eks-project
    instanceType: t2.small   
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 8
    amiFamily: AmazonLinux2
    labels: {role: worker}
    tags:
      nodegroup-role: worker    
    
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
      
    preBootstrapCommands:
      - sudo yum install -y amazon-efs-utils