apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql   
        - name: WORDPRESS_DB_NAME
          value: wordpress 
        - name: WORDPRESS_DB_USER
          value: admin     
        - name: WORDPRESS_DB_PASSWORD
          value: czB5lAtPbdDZa3iA           #Replace with RDS password
          #valueFrom:
            #secretKeyRef:
              #name: mysql-db-password
              #key: db-password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: efs-storage-claim
      #nodeSelector:
        #eks.amazonaws.com/nodegroup: ng-1